image: jangrewe/gitlab-ci-android

stages:
- build
- deploy

before_script:
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

deployRelease:
  stage: deploy
  script:
    - release.dir=app/build/outputs/
    - app.name=BestAppEver
    - email.to=$EMAIL_TARGET
